fastfinance.base.url=http://fastfinance-service:8000
fastfinance.request-timeout=5s
fastfinance.retry.max-attempts=2
fastfinance.retry.backoff=200ms

management.endpoint.health.show-details=when_authorized
management.endpoints.web.exposure.include=health,info,prometheus

spring.datasource.password=${STOCKCOMP_DATASOURCE_PASSWORD:}
spring.datasource.url=${STOCKCOMP_DATASOURCE_URL:jdbc:postgresql://postgres-service/stockdb}
spring.datasource.username=${STOCKCOMP_DATASOURCE_USERNAME:user}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.jakarta.persistence.sharedCache.mode=UNSPECIFIED

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
spring.security.oauth2.resourceserver.jwt.audience=https://api.stockcomp.local

spring.task.scheduling.pool.size=6

scheduling.enabled=true
scheduling.tasks.contest.maintain-contests.fixed-rate-ms=30000
scheduling.tasks.investment.maintain-investments.fixed-rate-ms=5000
scheduling.tasks.investment.maintain-investments.max-participants-per-run=1000
scheduling.tasks.investment-order.maintain-investment-orders.fixed-rate-ms=5000
scheduling.tasks.investment-order.maintain-investment-orders.max-participants-per-run=1000
scheduling.tasks.leaderboard.create-jobs.fixed-delay-ms=15000
scheduling.tasks.leaderboard.create-jobs.max-contests-per-run=1000
scheduling.tasks.leaderboard.process-jobs.fixed-delay-ms=5000

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
