access:
    token:
        duration: 60000

refresh:
    token:
        duration: 30

token:
    name: accessToken

consumer:
    base:
        url: http://stock-analyzer:8088

authorization:
    base:
        url: http://auth-backend-service

cookie:
    duration: 3600000

symbol:
    search:
        delay:
            time: 3600000

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,prometheus,env

spring:
    datasource:
        password: password
        url: jdbc:postgresql://postgres-service/stockdb
        username: user
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://auth-backend-service
                    jwk-set-uri: http://auth-backend-service/.well-known/jwks.json
