
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5432/stockdb
spring.datasource.username=user

fastfinance.base.url=http://localhost:8000

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:3050
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:3050/jwks
spring.security.oauth2.resourceserver.jwt.audience=https://api.stockcomp.local

scheduling.enabled=true
scheduling.tasks.contest.maintain-contests.fixed-rate-ms=30000
scheduling.tasks.investment.maintain-investments.fixed-rate-ms=100000
scheduling.tasks.investment-order.maintain-investment-orders.fixed-rate-ms=100000
scheduling.tasks.leaderboard.create-jobs.fixed-delay-ms=15000
scheduling.tasks.leaderboard.process-jobs.fixed-delay-ms=5000
