
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5432/stockdb
spring.datasource.username=user

fastfinance.base.url=http://localhost:8000

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:3050
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:3050/jwks
