access:
    token:
        duration: 60000

refresh:
    token:
        duration: 30

token:
    name: accessToken

consumer:
    base:
        url: http://stock-analyzer:8088

cookie:
    duration: 3600000

symbol:
    search:
        delay:
            time: 3600000

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,prometheus,env

spring:
    datasource:
        password: ${SPRING_DATASOURCE_PASSWORD}
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}

graphql:
    servlet:
        maxQueryDepth: 5
    graphiql:
        enabled: true



