apiVersion: batch/v1
kind: CronJob
metadata:
  name: process-investment-orders
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: process-orders
              image: curlimages/curl:7.87.0
              imagePullPolicy: IfNotPresent
              command:
                - curl
                - -v
                - -X
                - POST
                - http://stockcomp-service:8080/contest-operations/process-investment-orders

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: maintain-investments
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: maintain-investments
              image: curlimages/curl:7.87.0
              imagePullPolicy: IfNotPresent
              command:
                - curl
                - -v
                - -X
                - POST
                - http://stockcomp-service:8080/contest-operations/maintain-investments

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: maintain-contest-status
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: maintain-contest-status
              image: curlimages/curl:7.87.0
              imagePullPolicy: IfNotPresent
              command:
                - curl
                - -v
                - -X
                - POST
                - http://stockcomp-service:8080/contest-operations/maintain-contest-status

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-leaderboard
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: update-leaderboard
              image: curlimages/curl:7.87.0
              imagePullPolicy: IfNotPresent
              command:
                - curl
                - -v
                - -X
                - POST
                - http://stockcomp-service:8080/contest-operations/update-leaderboard