apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockcomp-deployment
  labels:
    app: stockcomp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockcomp
  template:
    metadata:
      labels:
        app: stockcomp
    spec:
      containers:
        - name: stockcomp
          image: stockcomp-server-image
          ports:
            - containerPort: 8080
          env:
            - name: ADMIN_EMAIL
              value: "admin@admin.com"
            - name: ADMIN_PASSWORD
              value: "admin"

---
apiVersion: v1
kind: Service
metadata:
  name: stockcomp-service
  labels:
    app: stockcomp
spec:
  selector:
    app: stockcomp
  ports:
    - name: http
      port: 8080
      targetPort: 8080

