apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockcomp-deployment
  labels:
    app: stockcomp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockcomp
  template:
    metadata:
      labels:
        app: stockcomp
    spec:
      containers:
        - name: stockcomp
          image: stockcomp-server-image
          ports:
            - containerPort: 8080
          env:
            - name: ADMIN_EMAIL
              value: "admin@admin.com"
            - name: ADMIN_PASSWORD
              value: "admin"

---
apiVersion: v1
kind: Service
metadata:
  name: stockcomp-service
spec:
  selector:
    app: stockcomp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30111

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-contest-server
spec:
  ingressClassName: nginx
  rules:
    - host: "contestserver.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stockcomp-service
                port:
                  number: 8080