apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockcomp-deployment
  labels:
    app: stockcomp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockcomp
  template:
    metadata:
      labels:
        app: stockcomp
    spec:
      containers:
        - name: stockcomp
          image: stockcomp-server-image
          ports:
            - containerPort: 8080
          env:
            - name: STOCKCOMP_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service/stockdb"
            - name: STOCKCOMP_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: stockcomp-postgres-credentials
                  key: username
            - name: STOCKCOMP_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stockcomp-postgres-credentials
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: stockcomp-service
  labels:
    app: stockcomp
spec:
  selector:
    app: stockcomp
  ports:
    - name: http
      port: 8080
      targetPort: 8080

