apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  database_url: jdbc:mysql://mysql-service:3306/stockcompdb?useSSL=false&allowPublicKeyRetrieval=true

---
#Generate secrets : echo -n '<value>' | base64
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  username: dXNlcg==
  password: cGFzc3dvcmQ=
  root-password: cm9vdA==
  jwt-secret: c2lsbHlqd3RzZWNyZXQ=