#Generate secrets : echo '<value>' | base64
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: dXNlcg==
  password: cGFzc3dvcmQ=
  root-password: cm9vdAo=