apiVersion: v1
kind: Service
metadata:
  name: stockcomp-service
  labels:
    app: stockcomp
spec:
  type: ClusterIP
  selector:
    app: stockcomp
  ports:
    - port: 8080
      targetPort: 8080
