apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockcomp-deployment
  labels:
    app: stockcomp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockcomp
  template:
    metadata:
      labels:
        app: stockcomp
    spec:
      containers:
        - name: stockcomp
          image: ghcr.io/andrewass/stockcomp:latest
          ports:
            - containerPort: 8080
          env:
            - name: CONSUMER_BASE_URL
              value: http://stock-analyzer:8088
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: database_url
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: password
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: username
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwt-secret

---
apiVersion: v1
kind: Service
metadata:
  name: stockcomp-service
spec:
  selector:
    app: stockcomp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
